In [385]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [386]:
df = pd.read_csv("~/python_decal_fa25/course_assignments/homework9/solar_system.csv")
df

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
5,Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
6,Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
7,Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
8,Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
9,Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
10,Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
11,Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
12,Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
13,Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
14,Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
15,Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
16,Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
17,Number of Moons,0,0,1,0,2,95,274,28,16,5
18,Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
19,Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [387]:
df1 = df.set_index("Attribute").T
df1.index.name = "Planet"
df1.reset_index(inplace=True)
df1.columns.name = None

df1

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [388]:
print(df.shape)

print(df1.shape)

(20, 11)
(10, 21)

In [389]:
"""
The shape before transposing = (20,11)

The shape after = (10,21)

The 1st line of code defines a new matrix where the previous matrix has been transposed.

It also makes the indexes for the new columns the attributes of the planets

The 2nd line of code sets the name of the index column as "Planets", since they are in fact the planets

The 3rd line of code retrieves the numbered index for the rows.

The 4th line of code removes the descriptors for the columns.

The new dataframe isn't 11 by 20 because we took the row naming all the attributes and made it the index in the new dataframe. So we will naturally

have 1 less row. We also made the planets their own column instead of an index, so we will naturally have 1 more column.
"""

'\nThe shape before transposing = (20,11)\n\nThe shape after = (10,21)\n\nThe 1st line of code defines a new matrix where the previous matrix has been transposed.\n\nIt also makes the indexes for the new columns the attributes of the planets\n\nThe 2nd line of code sets the name of the index column as "Planets", since they are in fact the planets\n\nThe 3rd line of code retrieves the numbered index for the rows.\n\nThe 4th line of code removes the descriptors for the columns.\n\nThe new dataframe isn\'t 11 by 20 because we took the row naming all the attributes and made it the index in the new dataframe. So we will naturally\n\nhave 1 less row. We also made the planets their own column instead of an index, so we will naturally have 1 more column.\n'

In [390]:
for i in df1.columns:
    print(i)

Planet
Mass (10^24kg)
Diameter (km)
Density (kg/m^3)
Gravity (m/s^2)
Escape Velocity (km/s)
Rotation Period (hours)
Length of Day (hours)
Distance from Sun (10^6 km)
Perihelion (10^6 km)
Aphelion (10^6 km)
Orbital Period (days)
Orbital Velocity (km/s)
Orbital Inclination (deg)
Orbital Eccentricity
Obliquity to Orbit (deg)
Mean Temperature (C)
Surface Pressure (bars)
Number of Moons
Ring System?
Global Magnetic Field?

In [391]:
units = 0
columns_with_units = []
columns_without_units = []
no_units = 0
for i in df1.columns:
    if ("(" in i) == True:
        units += 1
        columns_with_units.append(i)
    else:
        no_units += 1
        columns_without_units.append(i)

print(units)
print(columns_with_units)
print(no_units)
print(columns_without_units)

16
['Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)']
5
['Planet', 'Orbital Eccentricity', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']

In [392]:
df1.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [393]:
for i in df1.columns[1:]:
    print(df1[i].apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mass (10^24kg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Diameter (km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Density (kg/m^3), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Gravity (m/s^2), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Escape Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Rotation Period (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Length of Day (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Distance from Sun (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Perihelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Aphelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Period (days), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Inclination (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Eccentricity, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Obliquity to Orbit (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mean Temperature (C), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Surface Pressure (bars), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Number of Moons, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Ring System?, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Global Magnetic Field?, dtype: object

In [394]:
"""
The actual values are all strings. This is problematic for data analysis because we can't perform basic math operations (i.e mean) on strings.

"""

"\nThe actual values are all strings. This is problematic for data analysis because we can't perform basic math operations (i.e mean) on strings.\n\n"

In [395]:
df1.columns

for i in df1.columns:
    if (i != "Planet") & (i != "Ring System?") & (i != "Global Magnetic Field?"):
        df1[i] = pd.to_numeric(df1[i], errors="coerce")

In [396]:
df1.dtypes

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

In [397]:
for i in df1.columns:
    print(df1[i].apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Planet, dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Mass (10^24kg), dtype: object
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: Diameter (km), dtype: object
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: Density (kg/m^3), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Gravity (m/s^2), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Escape Velocity (km/s), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Rotation Period (hours), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Length of Day (hours), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Distance from Sun (10^6 km), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Perihelion (10^6 km), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Aphelion (10^6 km), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Orbital Period (days), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Orbital Velocity (km/s), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Orbital Inclination (deg), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Orbital Eccentricity, dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Obliquity to Orbit (deg), dtype: object
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: Mean Temperature (C), dtype: object
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: Surface Pressure (bars), dtype: object
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: Number of Moons, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Ring System?, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Global Magnetic Field?, dtype: object

In [398]:
"""
The three different types of data are now floats, integers, and objects.

float64 is a 64-bit float

int64 is a 64-bit integer

object is anything from mixed data types to strings to complex objects like dictionaries.

Planet, Ring System and Magnetic Field are still objects because they were kept as strings.
"""

'\nThe three different types of data are now floats, integers, and objects.\n\nfloat64 is a 64-bit float\n\nint64 is a 64-bit integer\n\nobject is anything from mixed data types to strings to complex objects like dictionaries.\n\nPlanet, Ring System and Magnetic Field are still objects because they were kept as strings.\n'

In [399]:
unit = 1e6 * u.km
old_col = 'Distance from Sun (10^6 km)'
new_col = 'Distance from Sun (km)'

def attach_units(column):
    new_values = []
    for i in df1[column]:
        new_values.append(i * unit)
    # print(new_values)
    df1[column] = new_values
    # print(df1[column])
    df1.rename(columns={old_col: new_col}, inplace=True)

attach_units('Distance from Sun (10^6 km)')

In [400]:
df1

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57900000.0 km,46.000,...,88.0,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108200000.0 km,107.500,...,224.7,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,12756,5514,9.8,11.2,23.9,24.0,149600000.0 km,147.100,...,365.2,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,384000.0 km,0.363,...,27.3,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228000000.0 km,206.700,...,687.0,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,142984,1326,23.1,59.5,9.9,9.9,778500000.0 km,740.600,...,4331.0,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,120536,687,9.0,35.5,10.7,10.7,1432000000.0 km,1357.600,...,10747.0,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867000000.0 km,2732.700,...,30589.0,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,49528,1638,11.0,23.5,16.1,16.1,4515000000.0 km,4471.100,...,59800.0,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2376,1850,0.7,1.3,-153.3,153.3,5906400000.0 km,4436.800,...,90560.0,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [401]:
x = df1['Perihelion (10^6 km)'].mean()
x

np.float64(1424.6462999999999)

In [402]:
y = df1['Aphelion (10^6 km)'].mean()
y

np.float64(1783.9605999999999)

In [403]:
semi_major_axis = (x+y)/2
semi_major_axis

np.float64(1604.3034499999999)

In [404]:
new_values = []
for i in range(10):
    new_values.append((df1['Perihelion (10^6 km)'].loc[i] + df1['Aphelion (10^6 km)'].loc[i])/2)

df1.insert(11, 'Semi-major Axis (10^6 km)', new_values)

df1

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57900000.0 km,46.000,...,88.0,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108200000.0 km,107.500,...,224.7,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,12756,5514,9.8,11.2,23.9,24.0,149600000.0 km,147.100,...,365.2,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,384000.0 km,0.363,...,27.3,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228000000.0 km,206.700,...,687.0,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,142984,1326,23.1,59.5,9.9,9.9,778500000.0 km,740.600,...,4331.0,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,120536,687,9.0,35.5,10.7,10.7,1432000000.0 km,1357.600,...,10747.0,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867000000.0 km,2732.700,...,30589.0,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,49528,1638,11.0,23.5,16.1,16.1,4515000000.0 km,4471.100,...,59800.0,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2376,1850,0.7,1.3,-153.3,153.3,5906400000.0 km,4436.800,...,90560.0,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [405]:
df1.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)',
       'Semi-major Axis (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [406]:
df1['Semi-major Axis (10^6 km)']

0      57.9000
1     108.2000
2     149.6000
3       0.3845
4     228.0000
5     778.5000
6    1432.0500
7    2867.0500
8    4515.0000
9    5906.3500
Name: Semi-major Axis (10^6 km), dtype: float64

In [407]:
unit = 1e6 * u.km
old_col = 'Semi-major Axis (10^6 km)'
new_col = 'Semi-major Axis (km)'

attach_units('Semi-major Axis (10^6 km)')

df1['Semi-major Axis (km)']

0      57900000.0 km
1     108200000.0 km
2     149600000.0 km
3        384500.0 km
4     228000000.0 km
5     778500000.0 km
6    1432050000.0 km
7    2867050000.0 km
8    4515000000.0 km
9    5906350000.0 km
Name: Semi-major Axis (km), dtype: object

In [408]:
df1['Orbital Period (days)']

0       88.0
1      224.7
2      365.2
3       27.3
4      687.0
5     4331.0
6    10747.0
7    30589.0
8    59800.0
9    90560.0
Name: Orbital Period (days), dtype: float64

In [412]:
new_val = []
for i in df1['Orbital Period (days)']:
    j = i * u.d
    # print(j.to(u.yr))
    new_val.append(j.to(u.yr))
df1['Orbital Period (days)'] = new_val

df1['Orbital Period (days)']

0    0.24093086926762491 yr
1     0.6151950718685831 yr
2     0.9998631074606433 yr
3    0.07474332648870637 yr
4     1.8809034907597535 yr
5      11.85763175906913 yr
6     29.423682409308693 yr
7      83.74811772758385 yr
8     163.72347707049965 yr
9     247.93976728268308 yr
Name: Orbital Period (days), dtype: object

In [413]:
df1.rename(columns={'Orbital Period (days)': 'Orbital Period (years)'}, inplace=True)

In [415]:
df1.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Semi-major Axis (km)',
       'Orbital Period (years)', 'Orbital Velocity (km/s)',
       'Orbital Inclination (deg)', 'Orbital Eccentricity',
       'Obliquity to Orbit (deg)', 'Mean Temperature (C)',
       'Surface Pressure (bars)', 'Number of Moons', 'Ring System?',
       'Global Magnetic Field?'],
      dtype='object')

In [414]:
df1['Orbital Period (years)']

0    0.24093086926762491 yr
1     0.6151950718685831 yr
2     0.9998631074606433 yr
3    0.07474332648870637 yr
4     1.8809034907597535 yr
5      11.85763175906913 yr
6     29.423682409308693 yr
7      83.74811772758385 yr
8     163.72347707049965 yr
9     247.93976728268308 yr
Name: Orbital Period (years), dtype: object

In [416]:
print(f"Saturn's orbital period is {df1['Orbital Period (years)'].loc[6]:.4f}")

Saturn's orbital period is 29.4237 yr

In [418]:
"""
An astronomical unit is the average distance from the Sun to the Earth
"""

const.au

<<class 'astropy.constants.iau2015.IAU2015'> name='Astronomical Unit' value=149597870700.0 uncertainty=0.0 unit='m' reference='IAU 2012 Resolution B2'>

In [419]:
x= const.au

x.to(u.km)

In [446]:
def converting_distances(column):
    new_val = []
    for i in df1[column]:
        j = i * u.km
        # print(j.to(u.yr))
        new_val.append(j.to(u.au))
    df1[column] = new_val

converting_distances('Diameter (km)')

df1.rename(columns={'Diameter (km)': 'Diameter (AU)'}, inplace=True)

In [427]:
converting_distances('Distance from Sun (km)')

df1.rename(columns={'Distance from Sun (km)': 'Distance from Sun (AU)'}, inplace=True)

In [431]:
converting_distances('Perihelion (10^6 km)')

df1.rename(columns={'Perihelion (10^6 km)': 'Perihelion (AU)'}, inplace=True)

In [442]:
df1

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (AU),...,Orbital Period (years),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,3.261410056954775e-05 AU,5429,3.7,4.3,1407.6,4222.6,0.387037594379343 AU,0.3074910076243485 AU,...,0.24093086926762491 yr,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,8.091024252793726e-05 AU,5243,8.9,10.4,-5832.5,2802.0,0.7232723266294458 AU,0.7185931156438579 AU,...,0.6151950718685831 yr,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,8.526859333165629e-05 AU,5514,9.8,11.2,23.9,24.0,1.0000142334913595 AU,0.9833027656856883 AU,...,0.9998631074606433 yr,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,2.3228940249882847e-05 AU,3340,1.6,2.4,655.7,708.7,0.002566881454951083 AU,0.0024265051253834456 AU,...,0.07474332648870637 yr,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,4.540171573444728e-05 AU,3934,3.7,5.0,24.6,24.7,1.5240858638772057 AU,1.3817041581728875 AU,...,1.8809034907597535 yr,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,0.0009557890050904314 AU,1326,23.1,59.5,9.9,9.9,5.2039510746859845 AU,4.950605222752011 AU,...,11.85763175906913 yr,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,0.0008057333933697493 AU,687,9.0,35.5,10.7,10.7,9.572328759088414 AU,9.07499547719164 AU,...,29.423682409308693 yr,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,0.0003417027245161184 AU,1270,8.7,21.3,-17.2,17.2,19.164711279543635 AU,18.26697122902298 AU,...,83.74811772758385 yr,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,0.0003310742309917116 AU,1638,11.0,23.5,16.1,16.1,30.180910857042033 AU,29.887457482374447 AU,...,163.72347707049965 yr,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,1.588257900250983e-05 AU,1850,0.7,1.3,-153.3,153.3,39.48184537896635 AU,29.65817614408064 AU,...,247.93976728268308 yr,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [433]:
converting_distances('Aphelion (10^6 km)')

df1.rename(columns={'Aphelion (10^6 km)': 'Aphelion (AU)'}, inplace=True)

In [440]:
# new_val = []
# for i in  df1['Perihelion (AU)']:
#     new_val.append(i * 1e6)
# df1['Perihelion (AU)'] = new_val

# Adjusting the perihelion and aphelion values

In [445]:
converting_distances('Semi-major Axis (km)')

df1.rename(columns={'Semi-major Axis (km)': 'Semi-major Axis (AU)'}, inplace=True)

In [454]:
df1['Diameter (AU)'].loc[6] # Saturn's diameter

In [455]:
df1['Distance from Sun (AU)'].loc[6] # Saturn's distance from the Sun

In [456]:
df1['Perihelion (AU)'].loc[6] # Saturn's perihelion

In [457]:
df1['Aphelion (AU)'].loc[6] # Saturn's aphelion

In [458]:
df1['Semi-major Axis (AU)'].loc[6] # Saturn's semi-major axis

In [459]:
df1.to_csv("units.csv", index=False)